
name: 'Godot 4 Web Export'
description: 'Godot Engine 4.x HTML5 export'
author: 'Simon Dalvai @dulvui'
branding:
  color: blue
  icon: upload-cloud

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  output-file-path:
    description: 'Path of the exported html files'
    required: false
    default: 'html5/index.html'
  create-export-preset-cfg:
    description: 'Set true if a simple export_presets.cfg should be created'
    required: false
    default: true
  godot-version:
    description: 'Godot Engine version. Supported are 4.x versions'
    required: false
    default: '4.1.3'
  
runs:
  using: "composite"
  steps:
    - name: Cache Godot files
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/godot/**
          /usr/local/bin/godot
          ~/.config/godot/**
        key: ${{ runner.os }}-godot-${{ inputs.godot-version }}

    - name: Download and config Godot Engine linux server and templates
      shell: bash
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: |
        wget -q https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
        wget -q https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
        mkdir ~/.cache
        mkdir -p ~/.config/godot
        mkdir -p ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
        unzip Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
        mv Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 /usr/local/bin/godot
        unzip Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
        rm -f Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
        godot --headless --editor --quit

    - name: Create export presets config
      if: ${{ inputs.create-export-preset-cfg  == 'true' }}
      shell: bash
      run: cp ${{ github.action_path }}/export_presets.cfg ${{ inputs.working-directory }}/export_presets.cfg

    - name: Create export paths directory structure
      shell: bash
      run: mkdir -p "$(dirname ${{ inputs.output-file-path }})"

    - name: Export Godot project to html
      shell: bash
      run: godot --headless --path ${{ inputs.working-directory }} --export-release Web ${{ inputs.output-file-path }}
